### ISSUE TITLE
CASAttributePrefix default shouldn't be "CAS_" (underscored)

### ISSUE THREAD

**Issue by mostolog** [apereo/mod_auth_cas#102]
Hi

Although there is a workaround (http://httpd.apache.org/docs/current/env.html#fixheader), default header prefix shouldn't use underscore to be Apache 2.4 friendly.
Of course, backward compatibility could be an issue here.

PS: Should CASAttributePrefix work on Location Context/Section?
Documentation states its a "Valid Directory/.htaccess Directives", although seems it doesn't work within _Location_. Probably I'm wrong, but perhaps it's an error...

Regards

**Comment by dhawes** [comment]
https://github.com/Jasig/mod_auth_cas/issues/49#issuecomment-55311020

**Comment by dhawes** [comment]
> PS: Should CASAttributePrefix work on Location Context/Section?
Documentation states its a "Valid Directory/.htaccess Directives", although seems it doesn't work within Location. Probably I'm wrong, but perhaps it's an error...

The documentation does state that it will work in Location, but it's configured as RSRC_CONF (top level or VirtualHost). I'll have to review to determine if it's a documentation or code update. CASAttributeDelimiter is the same way.

My inclination is to do a documentation update since I don't recall any requests to have it configurable in Directory/Location.

**Comment by dhawes** [comment]
Any preference for a better default?

""
"CAS"
"CAS-"

**Comment by mostolog** [comment]
> "CAS-" ?
