### ISSUE TITLE
Add support for longer tickets

### ISSUE THREAD

**Issue by cervantek** [apereo/mod_auth_cas#134]
The CAS server we are using (Shibboleth 3.3) allows for the encoding of new information in the ticket. This extra information removes the need for a  shared/distributed caching layer normally needed to support the serviceValidate in an HA configuration. This feature is great, and we have seen it working with the Apereo Java CAS client. Thanks to @serac for the great potential of this feature.

The only downside of this feature is that it makes the ticket longer.

mod_auth_cas works great with shorter tickets such as (42 characters, this was generated prior to enabling the feature described above):
 "ST-1508971678320-CKTeAedg9SNKl9QskdXZpAu5Y"

mod_auth_cas currently goes into a redirect loop when using longer tickets such as (325 characters, this was generated after enabling the feature described above):
 "ST-AAhzZWNyZXQyMsQg9zlvUgGTYTed4Dzavux5NST5KBg4GmU0KW9qLMvVmncGvS9XvEZbNlbtagBski9EOEinAXcKZFBosmstnRlNqghiyhYrFt9HriEbQIQomnnagomMYgXfqTpSfNsw1lMfMWfuBjioCLr0jsTmnwHH0oIQlb11D_3YJooo-FuX-9y37EiANxIlFwDQSQtLGF4w3OGqEuTIBfvMh-IC5ytDGV-PckYsx7IYWEmrmfpck6SxyvVF9dDeSV8rDSbYIru4LdJCMDe6UUrz0xZ2kH7EGXV_7PDknfALJq5gs0tqNhRMYPUwRw" 

I'd love to point out where in the codebase this could be addressed, but I am not a C developer.

Is this something that could be easily addressed?

Sincerely,
John Morton

**Comment by dhawes** [comment]
The problem is probably with the underscores ('_'). This should be trivial to fix. If characters other than '-', '.', '_', and alphanumerics are used, we'll need to know about them as well. 

Can you try the following patch and report back?

https://github.com/dhawes/mod_auth_cas/commit/a1d6284e796ab0724819537d92ac5d734b97f01d

**Comment by jeffreyindc** [comment]
I just want to add the if you set cas.ticket.security.cipherEnabled=true on your CAS server you get the same result.

**Comment by stanfran** [comment]
It appears that this is a difference in behavior between CAS 5.1 and 5.2.  In 5.1 and below, the set of characters possible in the random string portion of a service ticket was limited to alphanumerics.  In 5.2, it switched to the URL-safe variant of BASE64 which includes alphanumerics plus dashes and underscores.  The dashes don't matter because they were already used as delimiters of the different sections of the service tickets.  The addition of underscores is significant because service requests get stuck in a loop until they get a ticket back that happens not to contain one.  The final URL ends up retaining all of the unparsed ticket parameters.

**Comment by stanfran** [comment]
FYI, CAS 5.2.2 no longer includes underscores in service tickets.

**Comment by tsteiner** [comment]
I can confirm that allowing underscores allows the long tickets used by the shibboleth-idp 3.3 CAS implementation to work.

**Comment by serac** [comment]
@tsteiner, Shibboleth IdP 3.4 will contain a patch to constrain ticket identifiers to the protocol defined set, which does not include underscore. So it will be a moot point to support underscore. Support for longer tickets is still (desperately) needed.

**Comment by tsteiner** [comment]
@serac My point is that long tickets do seem to work, and that the actual problem is tickets containing underscores are considered invalid.

**Comment by stanfran** [comment]
@tsteiner Agreed.    

@serac It doesn't appear that there's a limitation on the length of the ticket parameter enforced by mod_auth_cas.  See [validCASTicketFormat](https://github.com/apereo/mod_auth_cas/blob/ac7147b33bfb48201b2de7d1e4400a43405c5480/src/mod_auth_cas.c#L663)  and [getCASTicket](https://github.com/apereo/mod_auth_cas/blob/ac7147b33bfb48201b2de7d1e4400a43405c5480/src/mod_auth_cas.c#L709).

Of course, the maximum length of the query string or the entire URL might be subject to limits in particular browser or HTTP server implementations.

**Comment by dhawes** [comment]
It's my understanding this is no longer an issue. Feel free to reopen if it is.

**Comment by tsteiner** [comment]
@dhawes Our IDP still gives out tickets with underscores in them, so I'm continuing to use a build containing dhawes@a1d6284.  Is there some reason not to merge this?  As far as I can tell, underscores aren't forbidden according to the [spec](https://apereo.github.io/cas/5.0.x/protocol/CAS-Protocol-Specification.html#311-service-ticket-properties):
> - Service tickets MUST begin with the characters, ST-.
> - Services MUST be able to accept service tickets of up to 32 characters in length. It is RECOMMENDED that services support service tickets of up to 256 characters in length.
