### ISSUE TITLE
Determine TLS version(s) CAS client will use?

### ISSUE THREAD

**Issue by cwaldbieser** [apereo/mod_auth_cas#199]
Is there some way to tell what TLS version(s) the CAS client in mod_auth_cas will use?  I have an application on a fairly old host that is using mod_auth_cas.  I tested limiting my CAS server to only accepting TLS 1.2 or better, and all my CAS clients (including several other mod_auth_cas clients) were able to work with the change except this particular one.

Is there a particular library that provides the TLS support that I can inspect to determine the underlying issue is?

**Comment by ruckc** [comment]
It should be based on whatever the httpd server supports with the underlying libcurl it's compiled against.  I can't think of a reason mod_auth_cas wouldn't support TLS 1.3 as long as libcurl does.

**Comment by dhawes** [comment]
I agree with @ruckc, it should work as long as your libcurl supports it.

Do you have the curl command on that system? Verify that it uses the same libcurl that mod_auth_cas uses (use "ldd mod_auth_cas.so" and "ldd `which curl`" or similar). Then "curl -v https://<CAS Server>" and look at the TLS output. Since you note that it's fairly old, I wouldn't be surprised at all if it didn't support newer TLS versions.

**Comment by cwaldbieser** [comment]
Thanks!  I kept looking at libssl, which was also linked, and I couldn't figure out why it wasn't using TLS1.2.
Looks like the mod_auth_cas.so on that host was compiled against a really old libcurl.

**Comment by cwaldbieser** [comment]
Closing
