### ISSUE TITLE
Request confirmation of status of mod_auth_cas with respect to CVE-2014-4172

### ISSUE THREAD

**Issue by rsajan** [apereo/mod_auth_cas#79]
The recent [CAS Client Security Vulnerability CVE-2014-4172](http://permalink.gmane.org/gmane.comp.java.jasig.cas.user/26914) lists 3 clients that are affected (Java, .NET, php) and states that _"There may be other CAS clients that are vulnerable."_ 

I've searched the page listed above as well as the [related comments page](http://comments.gmane.org/gmane.comp.java.jasig.cas.user/26914) and there is no mention of mod_auth_cas one way or the other. 

So I wanted to reach out to you here to see if you could confirm whether or not mod_auth_cas is vulnerable to CVE-2014-4172. 

FWIW I'm currently running version 1.0.8 - provided by Ubuntu package management (noticed the current version here is 1.0.10).

**Comment by PaulSD** [comment]
The vulnerability in the Java, .NET, and php clients was due to the fact that the ticket parameter was URL decoded when it was extracted from the URL, but was not URL encoded again when it was added to the validation URL.  Since mod_auth_cas does not URL decode the ticket parameter when extracting it from the URL, no version of mod_auth_cas is vulnerable to this issue.

When using SAML validation, mod_auth_cas v1.9.0.1 does allow some limited XML to be injected into the SAML request sent to the CAS server.  With the current parsing algorithm in the CAS server, I do not believe this exposes any vulnerabilities when using a CAS server, although it might expose vulnerabilities when using other SAMLv1.1 servers.  However, commit 59b6ea6cb1f8dddfaa616432a264ee403c10db37 (added after v1.0.9.1) adds additional validation which prevents this.

It looks like arbitrary (not limited as with mod_auth_cas) XML can be injected into SAML requests when using the latest Java CAS client ... I wonder if XML escaping and/or ticket syntax validation similar to that used in mod_auth_cas should be added to the Java CAS client to prevent this?
